# Generated by Django 5.2.6 on 2025-09-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Фильм"),
                            ("book", "Книга"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Текст цитаты")),
                ("weight", models.PositiveIntegerField(default=1, verbose_name="Вес")),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Лайки")),
                (
                    "dislikes",
                    models.PositiveIntegerField(default=0, verbose_name="Дизлайки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="quotes.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
            },
        ),
    ]
